---
title: "covidstats"
author: "Max Brehmer"
date: "5/2/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(utils)
library(tidyverse)
library(ISOweek)
library(stringi)
```

```{r, include=TRUE}
source("script_1.R", local = knitr::knit_global())
# or sys.source("your-script.R", envir = knitr::knit_global())

data <- read_csv("data.csv")

dataCut <- data %>%
  select(country, continent, population, indicator, weekly_count, year_week, rate_14_day, cumulative_count) %>%
  mutate(year_week = gsub("-", "-W", year_week), year_week = gsub("$", "-1", year_week), year_week = ISOweek2date(year_week)) %>%
  rename(date = year_week) %>%
  pivot_wider(names_from = indicator, values_from = c(weekly_count, rate_14_day, cumulative_count), values_fill = 0) %>%
  select(4,1:3,5:10) %>%
  arrange(date, country) %>%
  mutate(active_cases = 0)

for (i in 1:length(dataCut$active_cases)) {
  if (i >= 3) {
    dataCut[i, "active_cases"] <- dataCut[i, "cumulative_count_cases"] - dataCut[i-2, "cumulative_count_cases"] - dataCut[i, "weekly_count_deaths"] - dataCut[i-1, "weekly_count_deaths"]
  }
}

for (i in c("weekly_count_cases", "weekly_count_deaths", "rate_14_day_cases", "rate_14_day_deaths", "cumulative_count_cases", "cumulative_count_deaths", "active_cases")) {
  dataCut[paste(i, "per_capita", sep="_")] <- dataCut[i]/dataCut["population"]
}

#c(weekly_count_cases, weekly_count_deaths, rate_14_day_cases, rate_14_day_deaths, cumulative_count_cases, cumulative_count_deaths)

#knitr::kable(head(dataCut, 40))
dataCut
#dataCut2
```

